# This is a basic workflow to help you get started with Actions

name: Create Issue on Commit

# Controls when the workflow will run
on:
  repository_dispatch:
    types: next
  workflow_dispatch:  
  # Triggers the workflow on push or pull request events but only for the "main" branch
# push:
#    branches: [ "develop" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #  - uses: actions/checkout@v3

     # Runs a single command using the runners shell
       - name: create issue using REST API
         run: |
           curl --request POST \
           --url https://api.github.com/repos/${{ github.repository }}/issues \
           --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'content-type: application/json' \
            -H "X-GitHub-Api-Version: 2022-11-28" \
           --data '{
              "title": "automated Issue for commit: Test",
              "body": "This issue was automatically created by the github actions workflow **${{ github.workflow }}**. \n\n The commit has was: _test_."
              }'
        # - name: Trigger the other repository's workflow
        #   uses: peter-evans/repository-dispatch@v1
        #   with:
        #       repository: ${{ github.repository }}
        #       token: ${{ secrets.GITHUB_TOKEN }}
        #       event-type: doit
        #       client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      # - name: Create issue different
      #   run: |
      #     curl -L \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/repos/${{ github.repository }}/issues \
      #     -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["octocat"],"milestone":1,"labels":["bug"]}'


