# This is a basic workflow to help you get started with Actions

name: trigger workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trigger:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: trigger another workflow
          uses: |
              curl -X POST https://api.github.com/repos/:userName/:repoName/dispatches \
              -H 'Accept: application/vnd.github.everest-preview+json' \
              --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"${{ github.repository }}"'" }}'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #  - uses: actions/checkout@v3

      # Runs a single command using the runners shell


